/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as executable from "./executable";
import type * as interfaces from "./interfaces";

export type { executable };

export type { interfaces };
