/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DealClient } from "./DealClient";
export type { DealInfo } from "./DealInfo";
export type { SendMessage } from "./SendMessage";
export type { YourContractFactory } from "./YourContractFactory";
